version: '3.10'

services:
  browser:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      - JAVA_OPTS=-XX:ActiveProcessorCount=10
  web:
    build: .
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env.mongodb
  postgres:
    image: postgres:13
    env_file:
      - ./.env.postgres
    ports:
      - 5433:5432
